### ISSUE TITLE
comentarios avance 1

### ISSUE THREAD

**Issue by AliciaMstt** [heroduca/ProyectoFinalBioinf2018-II-#1]
Que bien que tengas datos propios :)

Por favor especifica en tu avance (modifica el archivo md). Lo siguiente:

1. ensamble de novo pero ¿de qué? ¿datos GBS? ¿genoma completo? ¿Secuenciados con Illumina HiSeq, MiSeq o PacBio o qué?

2. Especifica el repositorio y link al lugar de internet donde están los "datos de otros murciélagos ya disponibles en la red".

3. Describe con detalle a qué secuencias exactamente ya te dieron acceso.

**Comment by heroduca** [comment]
Hola Alicia, ya los atendí pero no me deja guardar, lo estoy haciendo desde mi repositorio del proyecto

**Comment by heroduca** [comment]
Ya lopude hacer, mi laptop me odia desde que murio en el salón :(

**Comment by AliciaMstt** [comment]
Hola, el link deNCBI que pusiste solo funciona desde la unam, el punto es estar seguras que puedes bajar los genomas. ¿es esto correcto?

**Comment by heroduca** [comment]
Hola Alicia, efectivamente aunque en realidad lo puse como de manera general y para buscar en la lupita del NCBI cada organismo, no sé si valdría la pena poner que especies son. Lo estaba pensando y llegue a la conclusión que no porque en realidad lo que te puse es para poner en contexto el por qué hacer un genoma de novo. Espero tus comentarios

**Comment by AliciaMstt** [comment]
Ya pude entrar al link. Lo que me preocupa es que puedas realmente bajar los datos de "para hacer un estudio filogenómico tomando datos de otros murciélagos que ya están disponibles en la red."

En tu avance 2 te pido que ya hayas bajado dichos datos para asegurarnos no tengas problema.

**Comment by heroduca** [comment]
Me parece perfecto y en su caso te diría cuales si pude bajar y cuales no
