### ISSUE TITLE
Comentarios avance 2

### ISSUE THREAD

**Issue by AliciaMstt** [heroduca/ProyectoFinalBioinf2018-II-#2]
Hola, me parece bien el cambio pero ¿ya tienes los datos de bacterias? Me gustaría que respondieras este issue modificando tu avance 2 para especificar de dónde sacarás los datos y que confirmes que ya los tienes en tu poder y exactamente qué análisis con que software realizarás.

Podemos acordar un avance 2.5 (respondiendo al issue, sin necesidad pull request) para dentro de una semana. ¿te parece?

Tu texto tiene algunas faltas de ortografía y no pusiste en cursivas los nombres científicos.

**Comment by heroduca** [comment]
Me parece perfecto, y lamento esos errores. En cuanto haga los cambios y ponga los links de donde obtuve los datos los pego. 
Dichas secuencias pienso bajarlas entre mañana y el jueves para poder hacer la investigación del software que usaré

**Comment by AliciaMstt** [comment]
Hola,

¿Cómo vas? Si aún no tienes los datos es momento de que te preocupes seriamente pues no te dará tiempo de lo contrario.

**Comment by heroduca** [comment]
Hola Alicia,

Lamento reportarme hasta ahora. He tenido un par de problemas personales y por esa razón no he podido avanzar en el proyecto. Pero igual venía a avisarte que no podré continuar con el curso (al menos lo que resta). 

Gracias y aún así trataré de ver los vídeos que me faltan para culminar el curso.

Saludos

**Comment by AliciaMstt** [comment]
Hola Dul. No te preocupes. Avísame si puedo ayudarte con algo. Si quieres después rpodemos revisar hasta donde llegaste en el proyecto para darte retroalimentación. Me avisas.
